#!/usr/bin/env bash
set -euo pipefail

mode="${1:---all}"
repo_root="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"

usage() {
    echo "Usage: $0 [--all|--static|--firmware]" >&2
}

run_static_checks() {
    local actionlint_bin
    local test_dir

    python3 tools/check_repo.py

    actionlint_bin="${ACTIONLINT_BIN:-}"
    if [[ -z "${actionlint_bin}" ]]; then
        actionlint_bin="$(command -v actionlint || true)"
    fi
    if [[ -z "${actionlint_bin}" || ! -x "${actionlint_bin}" ]]; then
        actionlint_bin="$(./tools/install-actionlint.sh)"
    fi
    "${actionlint_bin}" -color .github/workflows/*.yml

    test_dir="$(mktemp -d /tmp/ai-passport-host-tests.XXXXXX)"
    "${CC:-cc}" -std=c11 -Wall -Wextra -Werror -Imain \
        tests/test_ui_pixel_math.c main/ui_pixel_math.c \
        -o "${test_dir}/test_ui_pixel_math"
    "${test_dir}/test_ui_pixel_math"
    "${CC:-cc}" -std=c11 -Wall -Wextra -Werror -Imain \
        tests/test_muyu_merit.c main/muyu_merit.c \
        -o "${test_dir}/test_muyu_merit"
    "${test_dir}/test_muyu_merit"
    "${CC:-cc}" -std=c11 -Wall -Wextra -Werror -Imain \
        tests/test_muyu_inbox.c \
        -o "${test_dir}/test_muyu_inbox"
    "${test_dir}/test_muyu_inbox"
    python3 tests/test_verify_firmware.py
    rm -rf "${test_dir}"
    echo "Host tests: PASS"
}

run_firmware_checks() (
    local validation_build_dir
    local creds_file="${repo_root}/main/muyu_creds_local.h"
    local creds_generated=0

    # 转义 C 字符串里的 \ 和 " ,避免 SSID/密码含特殊字符时生成非法字面量。
    local esc_token esc_ssid esc_pass
    esc_token="${MUYU_INBOX_TOKEN:-}"; esc_token="${esc_token//\\/\\\\}"; esc_token="${esc_token//\"/\\\"}"
    esc_ssid="${MUYU_WIFI_SSID:-}";   esc_ssid="${esc_ssid//\\/\\\\}";   esc_ssid="${esc_ssid//\"/\\\"}"
    esc_pass="${MUYU_WIFI_PASS:-}";   esc_pass="${esc_pass//\\/\\\\}";   esc_pass="${esc_pass//\"/\\\"}"

    if ! command -v idf.py >/dev/null 2>&1; then
        echo "ERROR: idf.py is not available; activate ESP-IDF 5.5.3 first." >&2
        return 1
    fi

    validation_build_dir="$(mktemp -d /tmp/ai-passport-firmware.XXXXXX)"
    trap 'case "${validation_build_dir}" in /tmp/ai-passport-firmware.*) rm -rf -- "${validation_build_dir}" ;; esac; [[ "${creds_generated}" == 1 ]] && rm -f -- "${creds_file}"; true' EXIT

    # muyu_* 凭据:从 env(CI 由 repo secrets 注入,本地由开发者 export)生成
    # main/muyu_creds_local.h,构建结束即删除。
    #
    # 不走 idf.py -D:一是这些宏在代码里当字符串字面量用,-D 传引号极易出错;
    # 二是 idf_component_register 不接受 CFLAGS/CXXFLAGS 关键字,会被当成 include 目录而报
    # "Include directory .../main/CFLAGS is not a directory"。
    if [[ -n "${MUYU_INBOX_TOKEN:-}" && -n "${MUYU_WIFI_SSID:-}" && -n "${MUYU_WIFI_PASS:-}" ]]; then
        printf '#pragma once\n// Generated by tools/validate.sh from MUYU_* env. Do not commit.\n#define MUYU_INBOX_TOKEN "%s"\n#define MUYU_WIFI_SSID "%s"\n#define MUYU_WIFI_PASS "%s"\n' \
            "${esc_token}" "${esc_ssid}" "${esc_pass}" > "${creds_file}"
        creds_generated=1
        echo "Generated main/muyu_creds_local.h from MUYU_* env (deleted after build)."
    else
        echo "WARNING: no MUYU_* env vars; Muyu page will fail to compile"
        echo "         (MUYU_INBOX_TOKEN / MUYU_WIFI_SSID / MUYU_WIFI_PASS required)."
    fi

    SDKCONFIG_DEFAULTS="${repo_root}/sdkconfig.defaults" \
        idf.py -B "${validation_build_dir}" \
        -D "SDKCONFIG=${validation_build_dir}/sdkconfig" build
    idf.py -B "${validation_build_dir}" merge-bin \
        -o "${validation_build_dir}/FoloToy-AI-Passport-full.bin"
    python3 tools/verify_firmware.py "${validation_build_dir}"
    mkdir -p "${repo_root}/build"
    install -m 0644 \
        "${validation_build_dir}/FoloToy-AI-Passport-full.bin" \
        "${repo_root}/build/FoloToy-AI-Passport-full.bin"
    echo "Firmware build: PASS"
)

cd "${repo_root}"
case "${mode}" in
    --all)
        run_static_checks
        run_firmware_checks
        ;;
    --static)
        run_static_checks
        ;;
    --firmware)
        run_firmware_checks
        ;;
    *)
        usage
        exit 2
        ;;
esac
